version: "3.8"

services:
  nodejs-server:
    image: node:14
    container_name: nodejs-container
    working_dir: /server
    volumes:
      - ./:/server
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    # depends_on: # Uncomment after postgreSQL integration
    #  - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - pg-sql-data:/var/lib/postgresql/data # Provide pg-sql-data URL, for now its just a placeholder for testing

volumes:
  pg-sql-data:
# To run:
# docker-compose up
