version: "3.8"

services:
  nodejs-server:
    image: node:14
    container_name: nodejs-container
    working_dir: /server
    volumes:
      - ./:/server
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: olya
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgre-db-radency
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
# To run:
# docker-compose up
